### ISSUE TITLE
Support for v0.1 msh?

### ISSUE THREAD

**Issue by grazaerd** [Psycrow101/Blender-3D-DN-plugin#5]
Any possible support on it? Thanks!

**Comment by Psycrow101** [comment]
Send me a msh file of this version

**Comment by grazaerd** [comment]
[warrior_default_head.zip](https://github.com/Psycrow101/Blender-3D-DN-plugin/files/9571926/warrior_default_head.zip)

**Comment by Psycrow101** [comment]
Thanks for the feedback. I have updated the plugin. Try to import the meshes of this version now.
[io_scene_dragon_nest.zip](https://github.com/Psycrow101/Blender-3D-DN-plugin/files/9572424/io_scene_dragon_nest.zip)

**Comment by grazaerd** [comment]
Thanks! It works perfectly.
![image](https://user-images.githubusercontent.com/67945097/190367360-cb332900-eca3-4627-a6b3-396db0c3e6f9.png)
