### ISSUE TITLE
Incomplete mesh

### ISSUE THREAD

**Issue by grazaerd** [Psycrow101/Blender-3D-DN-plugin#7]
[frozen_dragon.zip](https://github.com/Psycrow101/Blender-3D-DN-plugin/files/14768395/frozen_dragon.zip)
![image](https://github.com/Psycrow101/Blender-3D-DN-plugin/assets/67945097/6ef54921-597c-48e7-9567-d253cd9e4886)

**Comment by Psycrow101** [comment]
Solved by https://github.com/Psycrow101/Blender-3D-DN-plugin/commit/aa8fa2a972e94fa7528bee80af0229602483f559
